### ISSUE TITLE
SAG - unable to update  payment method

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#29]
Not able to update the payment method for any easy pay customer (tried three different accounts) in Saginaw.

![sag_not able to update payment](https://cloud.githubusercontent.com/assets/25616655/23327971/bd09a756-fae4-11e6-8c13-df52c21e0dd2.png)

**Comment by mkoza178** [comment]
Try now. I had a wrong payway url. Updated.

**Comment by apattok** [comment]
Still not working....
![sag_not able to update payment2](https://cloud.githubusercontent.com/assets/25616655/23560567/ec640dc4-0008-11e7-8e8e-559bc91fe5fe.png)

**Comment by mkoza178** [comment]
Hey, that's because DTI error'd with: "Rate, Term, Length combination not valid"

Here's what we sent to them, can you tell if this is a DTI setup issue?
ActionType=RunProg&Progname=billchange&User=TEST&SubscriptionID=51097758&OccupantID=&AddressID=&ProductID=&TranDate=03/03/2017&SourceCode=SelfServ&Subsource=&ReasonCode=Update&BillingMethod=&BillPeriod=all&TipAmount=0&RateCode=VTUTHFSUREDUCEDD&Term=&Length=&RenewType=credit card&CardHolderName=Mark Stedman&TokenID=025039936&UniqueCustomerID=&CreditCardType=Visa&CreditCardNumber=************1111&CreditCardExpire=0319&BankType=&AccountType=&BankNumber=&AccountNumber=

**Comment by apattok** [comment]
I’ll get with IT. Thanks.

**Comment by apattok** [comment]
I believe it's because they are on a 5 week term and in DTI that's set to never show (even though it's built). I think that's what's hosing it. Jon is having similar issues with our 5 week terms on Easy Pay signups. Will find a non-5wk term person to test.

**Comment by apattok** [comment]
Confirmed a 4week account updated fine.
