### ISSUE TITLE
eBill signup option visible to subscriber already signed up for eBill

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#33]
Subscriber 265119 (David Milner), already receives eBills.  eBill signup still visible:

![image](https://cloud.githubusercontent.com/assets/25667903/23413694/131114ba-fd9f-11e6-877b-52c4ed6489dc.png)

**Comment by mkoza178** [comment]
I agree, it is still seen because we have not done any 'dynamic' processing of the navbar to show or not show specific items depending on your subscription variables.

If you go to eBill signup, you will see that the user is blocked though with a message that they are already on eBilling. 

This could be a future enhancement though to make the navbar display certain items depending on, if you're on ezpay, eBill, etc.

**Comment by beckywallace** [comment]
ok, I was just going based on what was on the UAT spreadsheet at the time which stated it should not be an option.  Thanks!

**Comment by mkoza178** [comment]
Oh that’s my fault then! I’ll update.
